In [1]:
import sys
if '../' not in sys.path:
    sys.path.append('../')
    sys.path.append('../src')
    
from Channel import Channel
from Solution import Solution

# Initialization
loading data and preprocessing

In [50]:
channel = Channel.read_testfile(4)

for i in range(Channel.N):
    channel[i].preprocess_simple()
    channel[i].preprocess_IP()
    channel[i].preprocess_LP()

In [51]:
S = Solution(channel)

# Greedy solution

In [54]:
%%time
S.greedy_solution()
S.get_answer(True)
S.show_answer(True)

Power budget: 16000
[0 1 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0]
[1 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0]
[0 1 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0]
[0 1 0 0 0]
[0 1 0 0 0 0 0]
[0 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0]
[0 1 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0]
[0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0]
[0 1 0 0 0 0]
[0 1 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0 0]
[0.         0.14705882 0.85294118 0.         0.         0.
 0.         0.        ]
[0 1 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0]
[0 1 0 0 0]
[0 0 1 0 0 0 0 0]
[0 1 0 0 0 0 0 0]
[0 1 0 0 0 0 0]
[1 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0 0]
[0 1 0 0 0 0]
[0 1 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0]
[0 1 0 0 0 0 

Standard linear programming for comparison

In [40]:
import numpy as np
from scipy import optimize

U = np.concatenate([channel[i].r for i in range(Channel.N)])
P = np.concatenate([channel[i].p for i in range(Channel.N)])
P = np.array([P])
B = Channel.P

X = np.zeros((Channel.N, len(U)))
temp = 0
for i in range(Channel.N):
    X[i, temp:temp+channel[i].size()] = 1
    temp += channel[i].size()

bounds = [(0, 1) for i in range(len(U))]

res = optimize.linprog(-U, A_ub=P, b_ub=B, A_eq=X, b_eq=[1 for i in range(Channel.N)], bounds=bounds)
print(res.x)
print(-res.fun)
#print(bounds)

[8.12776061e-10 1.00000000e+00 2.01016637e-10 1.79487182e-01
 8.20512820e-01 4.42324058e-10 1.00000000e+00 1.25750551e-10
 1.00000000e+00]
372.1538464519107


# DP solution

In [ ]:
%%time
S.DP_solution()
S.get_answer()
S.show_answer()

# DP solution 2

In [6]:
%%time
S.DP_solution_2()
S.get_answer()
S.show_answer()

Power budget: 100
channel(n)	 p	 r	 user(k), m
	 1 	 27 	 82 	 1 , 2
	 2 	 7 	 71 	 1 , 1
	 3 	 25 	 100 	 2 , 3
	 4 	 9 	 97 	 2 , 1
total power:  68 ; total utility:  350


# Branch and bound

In [7]:
%%time
S.BB_solution()
S.get_answer()
S.show_answer()

[[1, 2, 1, 1, 4]]
[[0, 2, 1, 1, 1], [1, 1, 1, 1, 2], [1, 2, 0, 1, 3], [1, 2, 1, 0, 4]]
[[1, 1, 1, 1, 2], [1, 2, 0, 1, 3], [1, 2, 1, 0, 4]]
[[1, 2, 0, 1, 3], [1, 2, 1, 0, 4]]
[[1, 2, 1, 0, 4]]
Power budget: 100
channel(n)	 p	 r	 user(k), m
	 1 	 27 	 82 	 1 , 2
	 2 	 7 	 71 	 1 , 1
	 3 	 25 	 100 	 2 , 3
	 4 	 9 	 97 	 2 , 1
total power:  68 ; total utility:  350
